-- RailDrop database — complete schema, in one script.
--
-- Paste the whole file into a new Supabase project's SQL editor and run it once.
-- It replaces running the nine files in supabase/migrations/ by hand, and it is
-- the same SQL in the same order, generated by scripts/build-setup-sql.mjs.
--
-- Safe to run more than once: every table, index and column is guarded with
-- "if not exists", and each policy is dropped before it is created (the
-- migrations themselves do not do that, because a migration only ever runs once).
--
-- After this, set three variables in Vercel -> Settings -> Environment Variables:
--   NEXT_PUBLIC_SUPABASE_URL        Project Settings -> Data API -> Project URL
--   NEXT_PUBLIC_SUPABASE_ANON_KEY   the anon / public key
--   SUPABASE_SERVICE_ROLE_KEY       the service_role key (server only, never
--                                   in a NEXT_PUBLIC_ variable)
-- then redeploy. See START_HERE_SUPABASE.md for the auth and redirect settings.

-- ───────────────────────────────────────────────────────────
-- 20260902100000_init.sql
-- ───────────────────────────────────────────────────────────
create extension if not exists pgcrypto;
create extension if not exists pg_trgm;

create table if not exists public.profiles (
  id uuid primary key,
  email text not null default '',
  timezone text not null default 'America/New_York',
  created_at timestamptz not null default now()
);

create table if not exists public.stations (
  code text primary key,
  name text not null,
  city text not null,
  state text not null,
  country text not null default 'US',
  latitude double precision,
  longitude double precision,
  refreshed_at timestamptz not null default now()
);

create table if not exists public.watches (
  id uuid primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  origin_code text not null,
  destination_code text not null,
  desired_travel_date date not null,
  date_flexibility_days smallint not null default 1 check (date_flexibility_days in (0, 1, 2)),
  preferred_departure_time text,
  passenger_count smallint not null default 1 check (passenger_count between 1 and 8),
  booked_train_number text,
  booked_departure_at timestamptz,
  booked_fare_family text not null default 'FLEXIBLE',
  travel_class text not null default 'COACH',
  current_booked_price_cents integer not null check (current_booked_price_cents >= 100),
  include_restricted_fares boolean not null default false,
  include_thruway boolean not null default false,
  minimum_savings_cents integer not null default 100,
  booked_at timestamptz not null,
  monitor_start_at timestamptz not null,
  monitor_end_at timestamptz,
  monitor_preset text not null default '48h',
  timezone text not null default 'America/New_York',
  alert_email text not null,
  status text not null default 'ACTIVE' check (status in ('ACTIVE', 'PAUSED', 'COMPLETED')),
  last_check_cycle_id uuid,
  last_checked_at timestamptz,
  next_check_slot text,
  next_check_at_label text,
  best_price_cents integer,
  best_savings_cents integer,
  last_opportunity jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.fare_check_cycles (
  id uuid primary key,
  watch_id uuid not null references public.watches(id) on delete cascade,
  trigger text not null check (trigger in ('INITIAL', 'SCHEDULED', 'MANUAL')),
  check_slot text,
  local_check_date date,
  status text not null,
  started_at timestamptz not null,
  completed_at timestamptz,
  dates_requested text[] not null default '{}',
  dates_succeeded text[] not null default '{}',
  dates_failed text[] not null default '{}',
  journeys_returned integer not null default 0,
  alerts_sent integer not null default 0,
  provider_requests integer not null default 0,
  reused_searches integer not null default 0
);

create table if not exists public.scheduled_check_runs (
  id uuid primary key,
  watch_id uuid not null references public.watches(id) on delete cascade,
  local_check_date date not null,
  check_slot text not null check (check_slot in ('MORNING', 'AFTERNOON', 'EVENING')),
  cycle_id text not null,
  created_at timestamptz not null default now(),
  unique (watch_id, local_check_date, check_slot)
);

create table if not exists public.provider_requests (
  id uuid primary key,
  search_key text not null,
  cycle_id uuid references public.fare_check_cycles(id) on delete set null,
  origin_code text not null,
  destination_code text not null,
  travel_date date not null,
  passenger_count smallint not null,
  status text not null,
  credits_consumed integer,
  latency_ms integer not null default 0,
  error_message text,
  reused_from_id uuid,
  created_at timestamptz not null default now()
);

create table if not exists public.fare_snapshots (
  id uuid primary key,
  cycle_id uuid not null references public.fare_check_cycles(id) on delete cascade,
  watch_id uuid not null references public.watches(id) on delete cascade,
  travel_date date not null,
  status text not null,
  search_key text not null,
  provider_request_id uuid,
  error_message text
);

create table if not exists public.journey_options (
  id uuid primary key,
  cycle_id uuid not null references public.fare_check_cycles(id) on delete cascade,
  watch_id uuid not null references public.watches(id) on delete cascade,
  travel_date date not null,
  payload jsonb not null
);

create table if not exists public.search_cache (
  provider_request_id uuid primary key,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.alerts (
  id uuid primary key,
  watch_id uuid not null references public.watches(id) on delete cascade,
  cycle_id uuid not null references public.fare_check_cycles(id) on delete cascade,
  fingerprint jsonb not null,
  subject text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.notification_deliveries (
  id uuid primary key,
  alert_id uuid not null references public.alerts(id) on delete cascade,
  watch_id uuid not null references public.watches(id) on delete cascade,
  to_email text not null,
  status text not null check (status in ('ATTEMPTED', 'ACCEPTED', 'FAILED')),
  provider_message_id text,
  error_message text,
  created_at timestamptz not null default now()
);

create table if not exists public.booking_price_events (
  id uuid primary key,
  watch_id uuid not null references public.watches(id) on delete cascade,
  previous_price_cents integer not null,
  new_price_cents integer not null,
  previous_travel_date date,
  new_travel_date date,
  note text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.provider_usage_daily (
  day date primary key,
  credits integer not null default 0,
  requests integer not null default 0,
  successes integer not null default 0,
  failures integer not null default 0
);

create index if not exists watches_user_id_idx on public.watches(user_id);
create index if not exists watches_status_idx on public.watches(status);
create index if not exists provider_requests_search_key_idx on public.provider_requests(search_key, created_at desc);
create index if not exists journey_options_watch_idx on public.journey_options(watch_id, cycle_id);
create index if not exists stations_search_idx on public.stations using gin (name gin_trgm_ops);

create or replace function public.increment_provider_usage(
  usage_day date,
  add_credits integer,
  add_requests integer,
  add_successes integer,
  add_failures integer
) returns void
language plpgsql
security definer
as $$
begin
  insert into public.provider_usage_daily as u (day, credits, requests, successes, failures)
  values (usage_day, add_credits, add_requests, add_successes, add_failures)
  on conflict (day) do update set
    credits = u.credits + excluded.credits,
    requests = u.requests + excluded.requests,
    successes = u.successes + excluded.successes,
    failures = u.failures + excluded.failures;
end;
$$;

alter table public.profiles enable row level security;
alter table public.watches enable row level security;
alter table public.fare_check_cycles enable row level security;
alter table public.scheduled_check_runs enable row level security;
alter table public.provider_requests enable row level security;
alter table public.fare_snapshots enable row level security;
alter table public.journey_options enable row level security;
alter table public.search_cache enable row level security;
alter table public.alerts enable row level security;
alter table public.notification_deliveries enable row level security;
alter table public.booking_price_events enable row level security;
alter table public.provider_usage_daily enable row level security;
alter table public.stations enable row level security;

drop policy if exists profiles_self on public.profiles;
create policy profiles_self on public.profiles
  for select using (auth.uid() = id);

drop policy if exists watches_self on public.watches;
create policy watches_self on public.watches
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists cycles_self on public.fare_check_cycles;
create policy cycles_self on public.fare_check_cycles
  for select using (
    exists (select 1 from public.watches w where w.id = watch_id and w.user_id = auth.uid())
  );

drop policy if exists snapshots_self on public.fare_snapshots;
create policy snapshots_self on public.fare_snapshots
  for select using (
    exists (select 1 from public.watches w where w.id = watch_id and w.user_id = auth.uid())
  );

drop policy if exists journeys_self on public.journey_options;
create policy journeys_self on public.journey_options
  for select using (
    exists (select 1 from public.watches w where w.id = watch_id and w.user_id = auth.uid())
  );

drop policy if exists alerts_self on public.alerts;
create policy alerts_self on public.alerts
  for select using (
    exists (select 1 from public.watches w where w.id = watch_id and w.user_id = auth.uid())
  );

drop policy if exists notifications_self on public.notification_deliveries;
create policy notifications_self on public.notification_deliveries
  for select using (
    exists (select 1 from public.watches w where w.id = watch_id and w.user_id = auth.uid())
  );

drop policy if exists price_events_self on public.booking_price_events;
create policy price_events_self on public.booking_price_events
  for select using (
    exists (select 1 from public.watches w where w.id = watch_id and w.user_id = auth.uid())
  );

drop policy if exists stations_read on public.stations;
create policy stations_read on public.stations
  for select using (true);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ───────────────────────────────────────────────────────────
-- 20260904140000_guest_profiles.sql
-- ───────────────────────────────────────────────────────────
-- REQUIRED for guest / optional sign-in on an existing RailDrop Supabase project.
-- SQL Editor → New query → paste → Run. Expect: Success. No rows returned.

alter table public.profiles drop constraint if exists profiles_id_fkey;
alter table public.profiles alter column email set default '';

-- ───────────────────────────────────────────────────────────
-- 20260925120000_scheduled_run_leases.sql
-- ───────────────────────────────────────────────────────────
-- Turn the scheduled-run claim into a lease.
--
-- The row was inserted before the work ran, keyed uniquely on
-- (watch_id, local_check_date, check_slot), and nothing ever updated it. So a
-- cron invocation that died partway through its loop left every watch it had
-- reached holding a consumed slot with no work done. The next hourly wake saw
-- the unique row, counted it as a duplicate, and moved on. Those travelers
-- were never checked and nothing logged an error.
--
-- A lease distinguishes "this slot is being worked on" from "this slot is
-- finished". A RUNNING row past its expiry is evidence of a crash, not of
-- completed work, and can be reclaimed.
--
-- cycle_id also has to stop being a lie: the dispatcher assigned it to a local
-- object after the cycle ran and never wrote it back, so every row in this
-- table says 'pending' forever. It becomes nullable, set on completion.

alter table public.scheduled_check_runs
  add column if not exists status text not null default 'PENDING'
    check (status in ('PENDING', 'RUNNING', 'DONE', 'FAILED', 'ABANDONED')),
  add column if not exists attempts smallint not null default 0,
  add column if not exists claimed_at timestamptz,
  add column if not exists started_at timestamptz,
  add column if not exists finished_at timestamptz,
  add column if not exists lease_expires_at timestamptz,
  add column if not exists failure_reason text;

-- Existing rows predate the lease. They were inserted only on the success path
-- of the old dispatcher, so treat them as finished rather than reclaimable —
-- reclaiming them would re-check historical slots on the first deploy.
update public.scheduled_check_runs
set status = 'DONE',
    finished_at = coalesce(finished_at, created_at)
where status = 'PENDING';

-- cycle_id was 'pending' on every row because the write-back never happened.
alter table public.scheduled_check_runs
  alter column cycle_id drop not null;

update public.scheduled_check_runs
set cycle_id = null
where cycle_id = 'pending';

-- The reaper asks one question: which leases have expired? And the enqueue
-- route asks: what is still owed? Both want this index.
create index if not exists scheduled_check_runs_lease_idx
  on public.scheduled_check_runs (status, lease_expires_at)
  where status in ('PENDING', 'RUNNING');

-- ─────────────────────────────────────────────────────────────────────────────
-- Down
--
--   drop index if exists public.scheduled_check_runs_lease_idx;
--
--   update public.scheduled_check_runs set cycle_id = 'pending' where cycle_id is null;
--   alter table public.scheduled_check_runs alter column cycle_id set not null;
--
--   alter table public.scheduled_check_runs
--     drop column if exists failure_reason,
--     drop column if exists lease_expires_at,
--     drop column if exists finished_at,
--     drop column if exists started_at,
--     drop column if exists claimed_at,
--     drop column if exists attempts,
--     drop column if exists status;
--
-- Reversible in structure. Not reversible in information: the down discards
-- which runs failed and why, because the old schema has nowhere to put it.
-- ─────────────────────────────────────────────────────────────────────────────

-- ───────────────────────────────────────────────────────────
-- 20260926090000_search_dedup_accounting.sql
-- ───────────────────────────────────────────────────────────
-- Make cross-watch search reuse measurable, and safe under fan-out.
--
-- Two separate problems.
--
-- 1. Reuse was invisible. Dedup already worked — findFreshSearch matches a
--    completed provider_requests row by canonical search_key inside a 20-minute
--    window, and the journeys come back from search_cache — but nothing counted
--    it. provider_usage_daily tracked credits, requests, successes and failures,
--    so the cost model in ARCHITECTURE.md could not be checked against reality:
--    there was no way to say how many Chromium runs the cache actually avoided.
--
-- 2. Fan-out introduced a race. While dispatch ran one watch at a time, the
--    second watch on a corridor always saw the first watch's finished row. Now
--    that each watch gets its own invocation, two workers can start the same
--    corridor and date in the same second, both miss the cache because neither
--    has finished, and both launch Chromium. The dedup is correct and still
--    silently pays for the collision.
--
--    An IN_FLIGHT marker lets the second worker see that someone is already
--    doing the work. provider_requests.status is free text, so the marker needs
--    no constraint change — but it does need an index, because the dedup lookup
--    scans by search_key and there has never been one.

alter table public.provider_usage_daily
  add column if not exists reused integer not null default 0;

-- The dedup lookup: newest completed row for a search key. Without this it is a
-- sequential scan of every provider request ever made, on every date of every
-- cycle.
create index if not exists provider_requests_search_key_idx
  on public.provider_requests (search_key, created_at desc);

-- ─────────────────────────────────────────────────────────────────────────────
-- Down
--
--   drop index if exists public.provider_requests_search_key_idx;
--   alter table public.provider_usage_daily drop column if exists reused;
--
-- Reversible in structure. The reuse counts are lost, which is acceptable:
-- they are an accounting aid, not a record of anything a traveler was told.
-- ─────────────────────────────────────────────────────────────────────────────

-- The accumulator has to learn the new column. Kept as a separate overload
-- signature rather than an in-place edit so a deploy that is mid-rollout — old
-- code calling the five-argument form, new code calling the six — works either
-- way for the minute that matters.
create or replace function public.increment_provider_usage(
  usage_day date,
  add_credits integer,
  add_requests integer,
  add_successes integer,
  add_failures integer,
  add_reused integer default 0
) returns void
language plpgsql
security definer
as $$
begin
  insert into public.provider_usage_daily as u (day, credits, requests, successes, failures, reused)
  values (usage_day, add_credits, add_requests, add_successes, add_failures, add_reused)
  on conflict (day) do update set
    credits = u.credits + excluded.credits,
    requests = u.requests + excluded.requests,
    successes = u.successes + excluded.successes,
    failures = u.failures + excluded.failures,
    reused = u.reused + excluded.reused;
end;
$$;

-- Down for the function: restore the five-argument body from the init
-- migration and drop the six-argument form.
--
--   drop function if exists public.increment_provider_usage(date, integer, integer, integer, integer, integer);

-- The in-flight marker has to be a claim, not an announcement.
--
-- Looking for a marker and then writing one is check-then-act: two workers
-- that look at the same instant both see nothing and both proceed, which is
-- exactly the race fan-out introduced. A partial unique index makes the insert
-- itself the arbiter — the loser gets 23505 and waits for the winner.
create unique index if not exists provider_requests_one_in_flight_idx
  on public.provider_requests (search_key)
  where status = 'IN_FLIGHT';

-- Down:
--   drop index if exists public.provider_requests_one_in_flight_idx;

-- ───────────────────────────────────────────────────────────
-- 20260926140000_alert_policy_state.sql
-- ───────────────────────────────────────────────────────────
-- Separate what we told a traveler from what we last saw.
--
-- watches.last_opportunity was doing both jobs, and the alert comparator asked
-- the wrong one. When qualifying options vanished the column kept the old
-- fingerprint, so:
--
--   told about $47 → it sells out → $60 appears, still $68 under their $128
--   → "is 60 at least 100 cents below 47?" → no → silence, forever.
--
-- The traveler holds an email about a fare that does not exist and is never
-- told about the one that does. Two columns, because they are two facts.
--
-- last_opportunity keeps its current meaning: the most recent observation.
-- last_alerted_opportunity is the fare we actually put in front of someone,
-- and it is the only thing a "worth another email?" comparison may be made
-- against.

alter table public.watches
  add column if not exists last_alerted_opportunity jsonb,
  -- Said once per lost opportunity, so a sold-out fare does not generate an
  -- email on every cycle for the rest of the window.
  add column if not exists opportunity_lost_notified boolean not null default false,
  -- The final last-call near departure, also once.
  add column if not exists departure_alert_sent boolean not null default false,
  -- 6.2: the re-alert threshold was hardcoded at 100 cents while
  -- PRODUCT_SPEC.md described the savings threshold as configurable. Null
  -- means "use the default", so existing watches keep today's behaviour.
  add column if not exists alert_improvement_cents integer;

-- Existing watches have been alerted against last_opportunity, so seed the new
-- column with it. Without this, every active watch would treat its next
-- qualifying find as a first_qualifying and send a duplicate opening email.
update public.watches
set last_alerted_opportunity = last_opportunity
where last_alerted_opportunity is null
  and last_opportunity is not null;

-- ─────────────────────────────────────────────────────────────────────────────
-- Down
--
--   alter table public.watches
--     drop column if exists alert_improvement_cents,
--     drop column if exists departure_alert_sent,
--     drop column if exists opportunity_lost_notified,
--     drop column if exists last_alerted_opportunity;
--
-- Reversible in structure. Reverting reintroduces the silence described above,
-- and loses which watches have already been told their option went.
-- ─────────────────────────────────────────────────────────────────────────────

-- ───────────────────────────────────────────────────────────
-- 20260926160000_email_suppression.sql
-- ───────────────────────────────────────────────────────────
-- A list of addresses we must not write to, and a reason for each.
--
-- A guest can put an email on a watch without an account. Until now there was
-- no unsubscribe link, no List-Unsubscribe header, and no way for that person
-- to identify themselves to us in order to ask us to stop. In most
-- jurisdictions that is unlawful; it is wrong regardless.
--
-- Keyed on the address rather than the watch: someone who asks to stop hearing
-- from us means all of it, not one trip. The reason is kept so an operator can
-- tell "they asked" from "the mailbox bounced" from "they called it spam" —
-- three different facts that deserve different handling.

create table if not exists public.email_suppressions (
  email text primary key,
  reason text not null check (reason in ('UNSUBSCRIBED', 'BOUNCED', 'COMPLAINED', 'MANUAL')),
  -- The watch the request came from, when there was one. Nulled if that watch
  -- is later deleted: the suppression must outlive it.
  watch_id uuid references public.watches(id) on delete set null,
  detail text,
  created_at timestamptz not null default now()
);

alter table public.email_suppressions enable row level security;

-- No policy is granted deliberately: this table is written and read by the
-- service role only. A suppression list readable by users would leak who has
-- complained, and one writable by users would let anyone silence anyone.

-- ─────────────────────────────────────────────────────────────────────────────
-- Down
--
--   drop table if exists public.email_suppressions;
--
-- Reversible, and destructive in a way that matters: dropping this table
-- resumes mail to people who asked us to stop. Do not run it to "clean up".
-- ─────────────────────────────────────────────────────────────────────────────

-- ───────────────────────────────────────────────────────────
-- 20260926180000_alert_decisions.sql
-- ───────────────────────────────────────────────────────────
-- Why we spoke, and why we didn't.
--
-- Every cycle makes an alert decision and, until now, only the positive ones
-- left a trace: an alert row exists when mail was sent, and nothing at all
-- exists when it was not. So "why didn't you tell me about the $60?" had no
-- answer beyond re-deriving it from code and hoping the inputs were the same.
--
-- The silences are the interesting half. This records both, with the two
-- fingerprints that produced the decision and the sentence the policy wrote at
-- the time, so the answer months later is the reasoning as it actually ran
-- rather than as we would reconstruct it.

create table if not exists public.alert_decisions (
  id uuid primary key,
  watch_id uuid not null references public.watches(id) on delete cascade,
  cycle_id uuid references public.fare_check_cycles(id) on delete set null,
  -- first_qualifying | better_price | opportunity_lost | new_opportunity |
  -- worse_but_qualifying | departure_imminent | no_qualifying | unchanged
  reason text not null,
  notified boolean not null,
  -- What the traveler had been told, and what this cycle saw. Snapshots, so a
  -- later change to the watch cannot rewrite the record of the decision.
  alerted_fingerprint jsonb,
  observed_fingerprint jsonb,
  explanation text not null,
  created_at timestamptz not null default now()
);

create index if not exists alert_decisions_watch_idx
  on public.alert_decisions (watch_id, created_at desc);

alter table public.alert_decisions enable row level security;

-- Readable by the owner of the watch: this is the traveler's own answer to
-- "why didn't you tell me". Writes are service-role only.
drop policy if exists "alert_decisions_select_own" on public.alert_decisions;
drop policy if exists "alert_decisions_select_own" on public.alert_decisions;
create policy "alert_decisions_select_own" on public.alert_decisions
  for select using (
    exists (
      select 1 from public.watches w
      where w.id = alert_decisions.watch_id and w.user_id = auth.uid()
    )
  );

-- ─────────────────────────────────────────────────────────────────────────────
-- Down
--
--   drop table if exists public.alert_decisions;
--
-- Reversible. Discards the record of why past alerts were or were not sent,
-- which cannot be reconstructed afterwards.
-- ─────────────────────────────────────────────────────────────────────────────

-- ───────────────────────────────────────────────────────────
-- 20260926200000_cycle_observed_price.sql
-- ───────────────────────────────────────────────────────────
-- What the board actually saw, each time it looked.
--
-- The watch page has a panel headed "Price history" that plots
-- booking_price_events — the traveler's own benchmark, which only changes when
-- they press "I rebooked". For almost every watch that is a single point, and
-- for none of them is it a history of fares. The product checks a corridor
-- three times a day and threw away every observation but the latest.
--
-- Two columns on the cycle, written when it completes. A cycle is already the
-- record of one look at the market; this is what that look found. Deriving it
-- instead — min() over journey_options per cycle — is a join across the largest
-- table in the schema on every board render, to recompute a number that was in
-- memory at the moment it was known.
--
-- Nullable because a cycle can legitimately find nothing: a provider outage, or
-- a corridor with no listed inventory. NULL means "looked, saw nothing", which
-- is a different fact from 0 and from a missing row, and the chart draws it as
-- a gap rather than a crash to zero.

alter table public.fare_check_cycles
  add column if not exists best_price_cents integer,
  add column if not exists best_travel_date date;

comment on column public.fare_check_cycles.best_price_cents is
  'Cheapest eligible total party fare observed in this cycle. NULL = nothing qualified.';
comment on column public.fare_check_cycles.best_travel_date is
  'Which day in the window that cheapest fare was on.';

-- The chart reads the last N cycles for one watch, newest first.
create index if not exists fare_check_cycles_watch_started_idx
  on public.fare_check_cycles (watch_id, started_at desc);

-- Backfill from what is already stored, so the history does not start empty for
-- watches that have been running. journey_options holds every option each cycle
-- returned; the cheapest of them is the observation that cycle made.
--
-- Deliberately narrow: only rows that returned something, and only the total
-- party price, which is the figure the board ranks on. Anything it cannot work
-- out honestly stays NULL.
update public.fare_check_cycles as c
set best_price_cents = sub.cheapest
from (
  select
    j.cycle_id,
    min((j.option -> 'fares' -> 0 ->> 'totalPartyPriceCents')::integer) as cheapest
  from public.journey_options as j
  where j.option -> 'fares' -> 0 ->> 'totalPartyPriceCents' is not null
  group by j.cycle_id
) as sub
where sub.cycle_id = c.id
  and c.best_price_cents is null
  and sub.cheapest is not null
  and sub.cheapest > 0;

-- ───────────────────────────────────────────────────────────
-- 20260927100000_corridor_history.sql
-- ───────────────────────────────────────────────────────────
-- What a corridor costs, from every search we have ever run.
--
-- provider_requests already records origin, destination, travel date and time
-- for every search, across every user. It does not record what the search
-- found. So each watch starts blind: a new BOS→NYP watch says "we have no price
-- history for this trip yet" and gives a low-confidence recommendation, while
-- the product has been scraping that exact corridor three times a day for
-- somebody else all week.
--
-- One column closes that. It is the cheapest believable fare the search
-- returned — believable meaning it passed fare-sanity, so a misparse cannot
-- drag a corridor's floor down and make every traveler on it think they
-- overpaid.
--
-- NULL means the search found nothing, or failed, or was never completed. A
-- corridor summary counts only rows that have a price, and says how many.

alter table public.provider_requests
  add column if not exists cheapest_price_cents integer;

comment on column public.provider_requests.cheapest_price_cents is
  'Cheapest plausible total-party fare this search returned, at one adult. NULL = found nothing, failed, or still in flight.';

-- The corridor query: one origin-destination pair, recent first.
-- Partial, because a row with no price is never in the answer and there are a
-- lot of them (errors, in-flight claims, empty inventory).
create index if not exists provider_requests_corridor_idx
  on public.provider_requests (origin_code, destination_code, created_at desc)
  where cheapest_price_cents is not null;

-- Backfill from what is already stored. journey_options holds every option each
-- cycle returned; provider_requests and cycles are joined through the snapshot
-- that recorded the search. Only rows we can attribute confidently are filled —
-- anything ambiguous stays NULL, because a wrong number here becomes a claim
-- about what a corridor costs.
update public.provider_requests as pr
set cheapest_price_cents = sub.cheapest
from (
  select
    s.provider_request_id,
    min((j.option -> 'fares' -> 0 ->> 'totalPartyPriceCents')::integer) as cheapest
  from public.fare_snapshots as s
  join public.journey_options as j
    on j.cycle_id = s.cycle_id
   and j.travel_date = s.travel_date
  where s.provider_request_id is not null
    and j.option -> 'fares' -> 0 ->> 'totalPartyPriceCents' is not null
  group by s.provider_request_id
) as sub
where sub.provider_request_id = pr.id
  and pr.cheapest_price_cents is null
  and sub.cheapest is not null
  -- The same floor fare-sanity uses. A backfilled misparse is still a misparse.
  and sub.cheapest >= 300;

