import { chromium } from 'playwright';
const OUT='/private/tmp/claude-501/-Users-johnjayasankar-Documents-GitHub-RailDrop3/a0693671-7431-48fb-989a-d258ff4cf122/scratchpad/shots';
const base='http://127.0.0.1:3212';
const b=await chromium.launch();
const ctx=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2});
const p=await ctx.newPage();
await p.goto(base+'/',{waitUntil:'networkidle'});
await p.fill('input[name=on]','2026-10-15');
await p.click('button.hero-go');
await p.waitForLoadState('networkidle');
await p.waitForTimeout(2500);
console.log('URL ->', p.url());
console.log('body text snippet ->', (await p.locator('main').innerText()).replace(/\n+/g,' | ').slice(0,700));
await p.screenshot({path:`${OUT}/hero-submit-390.png`, fullPage:true});
// past date test
await p.goto(base+'/',{waitUntil:'networkidle'});
await p.fill('input[name=on]','2020-01-01');
await p.click('button.hero-go');
await p.waitForLoadState('networkidle');
await p.waitForTimeout(1500);
console.log('PAST URL ->', p.url());
console.log('PAST text ->', (await p.locator('main').innerText()).replace(/\n+/g,' | ').slice(0,500));
await p.screenshot({path:`${OUT}/hero-past-390.png`, fullPage:true});
await b.close();
