-- ════════════════════════════════════════════════════════════════════════════
-- RailDrop - station catalog bootstrap
--
-- A curated set of high-traffic Amtrak stations so the app is usable immediately
-- and station typeahead costs ZERO provider credits.
--
-- This is a BOOTSTRAP, not the source of truth. Run
--     npm run refresh:stations
-- to replace it with the provider's own `get_stations` catalog (one call).
-- ════════════════════════════════════════════════════════════════════════════

insert into public.stations (code, name, city, state, timezone) values
  ('BOS','Boston South Station','Boston','MA','America/New_York'),
  ('BBY','Boston Back Bay','Boston','MA','America/New_York'),
  ('BON','Boston North Station','Boston','MA','America/New_York'),
  ('RTE','Route 128','Westwood','MA','America/New_York'),
  ('PVD','Providence','Providence','RI','America/New_York'),
  ('KIN','Kingston','Kingston','RI','America/New_York'),
  ('WLY','Westerly','Westerly','RI','America/New_York'),
  ('MYS','Mystic','Mystic','CT','America/New_York'),
  ('NLC','New London','New London','CT','America/New_York'),
  ('OSB','Old Saybrook','Old Saybrook','CT','America/New_York'),
  ('NHV','New Haven Union Station','New Haven','CT','America/New_York'),
  ('BRP','Bridgeport','Bridgeport','CT','America/New_York'),
  ('STM','Stamford','Stamford','CT','America/New_York'),
  ('HFD','Hartford','Hartford','CT','America/New_York'),
  ('SPG','Springfield','Springfield','MA','America/New_York'),
  ('NYP','New York Penn Station','New York','NY','America/New_York'),
  ('NWK','Newark Penn Station','Newark','NJ','America/New_York'),
  ('EWR','Newark Liberty Airport','Newark','NJ','America/New_York'),
  ('MET','Metropark','Iselin','NJ','America/New_York'),
  ('TRE','Trenton','Trenton','NJ','America/New_York'),
  ('PHL','Philadelphia 30th Street','Philadelphia','PA','America/New_York'),
  ('WIL','Wilmington','Wilmington','DE','America/New_York'),
  ('ABE','Aberdeen','Aberdeen','MD','America/New_York'),
  ('BAL','Baltimore Penn Station','Baltimore','MD','America/New_York'),
  ('BWI','BWI Thurgood Marshall Airport','Baltimore','MD','America/New_York'),
  ('NCR','New Carrollton','New Carrollton','MD','America/New_York'),
  ('WAS','Washington Union Station','Washington','DC','America/New_York'),
  ('ALX','Alexandria','Alexandria','VA','America/New_York'),
  ('FBG','Fredericksburg','Fredericksburg','VA','America/New_York'),
  ('RVR','Richmond Staples Mill Road','Richmond','VA','America/New_York'),
  ('RVM','Richmond Main Street','Richmond','VA','America/New_York'),
  ('PTB','Petersburg','Petersburg','VA','America/New_York'),
  ('CVS','Charlottesville','Charlottesville','VA','America/New_York'),
  ('LYH','Lynchburg','Lynchburg','VA','America/New_York'),
  ('RNK','Roanoke','Roanoke','VA','America/New_York'),
  ('NFK','Norfolk','Norfolk','VA','America/New_York'),
  ('NPN','Newport News','Newport News','VA','America/New_York'),
  ('WBG','Williamsburg','Williamsburg','VA','America/New_York'),
  ('GBO','Greensboro','Greensboro','NC','America/New_York'),
  ('RGH','Raleigh','Raleigh','NC','America/New_York'),
  ('CLT','Charlotte','Charlotte','NC','America/New_York'),
  ('FAY','Fayetteville','Fayetteville','NC','America/New_York'),
  ('CHS','Charleston','Charleston','SC','America/New_York'),
  ('CLB','Columbia','Columbia','SC','America/New_York'),
  ('SAV','Savannah','Savannah','GA','America/New_York'),
  ('ATL','Atlanta Peachtree','Atlanta','GA','America/New_York'),
  ('JAX','Jacksonville','Jacksonville','FL','America/New_York'),
  ('ORL','Orlando','Orlando','FL','America/New_York'),
  ('WPK','Winter Park','Winter Park','FL','America/New_York'),
  ('TPA','Tampa Union Station','Tampa','FL','America/New_York'),
  ('WPB','West Palm Beach','West Palm Beach','FL','America/New_York'),
  ('FTL','Fort Lauderdale','Fort Lauderdale','FL','America/New_York'),
  ('MIA','Miami','Miami','FL','America/New_York'),
  ('ALB','Albany-Rensselaer','Albany','NY','America/New_York'),
  ('POU','Poughkeepsie','Poughkeepsie','NY','America/New_York'),
  ('CRT','Croton-Harmon','Croton-on-Hudson','NY','America/New_York'),
  ('YNY','Yonkers','Yonkers','NY','America/New_York'),
  ('HUD','Hudson','Hudson','NY','America/New_York'),
  ('RHI','Rhinecliff','Rhinecliff','NY','America/New_York'),
  ('SDY','Schenectady','Schenectady','NY','America/New_York'),
  ('UCA','Utica','Utica','NY','America/New_York'),
  ('SYR','Syracuse','Syracuse','NY','America/New_York'),
  ('ROC','Rochester','Rochester','NY','America/New_York'),
  ('BUF','Buffalo Depew','Buffalo','NY','America/New_York'),
  ('BFX','Buffalo Exchange Street','Buffalo','NY','America/New_York'),
  ('NFL','Niagara Falls','Niagara Falls','NY','America/New_York'),
  ('PLB','Plattsburgh','Plattsburgh','NY','America/New_York'),
  ('BRA','Brattleboro','Brattleboro','VT','America/New_York'),
  ('ESX','Essex Junction','Essex Junction','VT','America/New_York'),
  ('WRJ','White River Junction','White River Junction','VT','America/New_York'),
  ('PIT','Pittsburgh','Pittsburgh','PA','America/New_York'),
  ('HAR','Harrisburg','Harrisburg','PA','America/New_York'),
  ('LNC','Lancaster','Lancaster','PA','America/New_York'),
  ('PAO','Paoli','Paoli','PA','America/New_York'),
  ('ERI','Erie','Erie','PA','America/New_York'),
  ('CLE','Cleveland','Cleveland','OH','America/New_York'),
  ('TOL','Toledo','Toledo','OH','America/New_York'),
  ('CIN','Cincinnati','Cincinnati','OH','America/New_York'),
  ('IND','Indianapolis','Indianapolis','IN','America/New_York'),
  ('SOB','South Bend','South Bend','IN','America/New_York'),
  ('DET','Detroit','Detroit','MI','America/New_York'),
  ('ARB','Ann Arbor','Ann Arbor','MI','America/New_York'),
  ('GRR','Grand Rapids','Grand Rapids','MI','America/New_York'),
  ('CHI','Chicago Union Station','Chicago','IL','America/Chicago'),
  ('MKE','Milwaukee','Milwaukee','WI','America/Chicago'),
  ('MSP','Saint Paul-Minneapolis','Saint Paul','MN','America/Chicago'),
  ('STL','St. Louis','St. Louis','MO','America/Chicago'),
  ('KCY','Kansas City','Kansas City','MO','America/Chicago'),
  ('SPI','Springfield','Springfield','IL','America/Chicago'),
  ('CHM','Champaign-Urbana','Champaign','IL','America/Chicago'),
  ('MEM','Memphis','Memphis','TN','America/Chicago'),
  ('BHM','Birmingham','Birmingham','AL','America/Chicago'),
  ('NOL','New Orleans','New Orleans','LA','America/Chicago'),
  ('HOS','Houston','Houston','TX','America/Chicago'),
  ('SAS','San Antonio','San Antonio','TX','America/Chicago'),
  ('AUS','Austin','Austin','TX','America/Chicago'),
  ('DAL','Dallas Union Station','Dallas','TX','America/Chicago'),
  ('FTW','Fort Worth','Fort Worth','TX','America/Chicago'),
  ('ELP','El Paso','El Paso','TX','America/Denver'),
  ('ABQ','Albuquerque','Albuquerque','NM','America/Denver'),
  ('DEN','Denver Union Station','Denver','CO','America/Denver'),
  ('GJT','Grand Junction','Grand Junction','CO','America/Denver'),
  ('SLC','Salt Lake City','Salt Lake City','UT','America/Denver'),
  ('FLG','Flagstaff','Flagstaff','AZ','America/Phoenix'),
  ('TUS','Tucson','Tucson','AZ','America/Phoenix'),
  ('RNO','Reno','Reno','NV','America/Los_Angeles'),
  ('SAC','Sacramento','Sacramento','CA','America/Los_Angeles'),
  ('EMY','Emeryville','Emeryville','CA','America/Los_Angeles'),
  ('OKJ','Oakland Jack London Square','Oakland','CA','America/Los_Angeles'),
  ('SJC','San Jose Diridon','San Jose','CA','America/Los_Angeles'),
  ('SLO','San Luis Obispo','San Luis Obispo','CA','America/Los_Angeles'),
  ('SBA','Santa Barbara','Santa Barbara','CA','America/Los_Angeles'),
  ('LAX','Los Angeles Union Station','Los Angeles','CA','America/Los_Angeles'),
  ('ANA','Anaheim','Anaheim','CA','America/Los_Angeles'),
  ('IRV','Irvine','Irvine','CA','America/Los_Angeles'),
  ('SNA','Santa Ana','Santa Ana','CA','America/Los_Angeles'),
  ('SAN','San Diego Santa Fe Depot','San Diego','CA','America/Los_Angeles'),
  ('BFD','Bakersfield','Bakersfield','CA','America/Los_Angeles'),
  ('FNO','Fresno','Fresno','CA','America/Los_Angeles'),
  ('KFS','Klamath Falls','Klamath Falls','OR','America/Los_Angeles'),
  ('EUG','Eugene','Eugene','OR','America/Los_Angeles'),
  ('PDX','Portland Union Station','Portland','OR','America/Los_Angeles'),
  ('SEA','Seattle King Street Station','Seattle','WA','America/Los_Angeles'),
  ('TAC','Tacoma','Tacoma','WA','America/Los_Angeles'),
  ('BEL','Bellingham','Bellingham','WA','America/Los_Angeles'),
  ('SPK','Spokane','Spokane','WA','America/Los_Angeles'),
  ('VAC','Vancouver','Vancouver','BC','America/Vancouver')
on conflict (code) do update
  set name = excluded.name,
      city = excluded.city,
      state = excluded.state,
      timezone = excluded.timezone,
      updated_at = now();
