import { describeActiveProvider } from '@/lib/providers';

/**
 * Says out loud when the fares on screen are not real.
 *
 * A deployment running the deterministic provider renders prices, charts,
 * savings and alerts that look exactly like live ones, because they go through
 * exactly the same pipeline. That is the point of the harness and it is also a
 * hazard: nothing on screen distinguished a generated $62.05 from an observed
 * one, so anybody shown a demo could reasonably believe they were looking at
 * Amtrak's prices.
 *
 * Renders nothing at all on a deployment with a live provider, so it costs a
 * real installation nothing.
 */
export function DemoBanner() {
  const provider = describeActiveProvider();
  if (provider.isLive) return null;

  return (
    <div role="status" data-testid="demo-banner" className="border-b border-warn-line bg-warn-soft">
      <div className="mx-auto flex max-w-5xl flex-wrap items-baseline gap-x-2 gap-y-0.5 px-4 py-2 sm:px-6">
        <span className="text-[12px] font-bold uppercase tracking-[0.09em] text-warn">
          Demo data
        </span>
        <span className="text-[12.5px] leading-relaxed text-warn/90">
          Every fare here is generated by a deterministic test provider — realistic, repeatable and
          not an Amtrak price. Nothing on this deployment is a real quote.
        </span>
      </div>
    </div>
  );
}
